---
title: "Ridge logitstic regression"
author: "Gabrielle Voiseux"
date: "08/06/2021"
output: html_document
---


The dataset also must be loaded.


```{r}
library("tidymodels")
library("readr")
library("glmnet")
library("kernlab")
library(themis)
library(dplyr)
library(tidyverse)
```


```{r}
fraud <- read.csv("final_data.csv") %>% select(-X, -period, -fyear)

```


```{r}
fraud$misstate <- as.factor(fraud$misstate)
fraud$bf_1 <- as.factor(fraud$bf_1)
fraud$bf_2 <- as.factor(fraud$bf_2)
fraud$bf_3 <- as.factor(fraud$bf_3)
fraud$bf_agr <- as.factor(fraud$bf_agr)
#fraud$fyear <- as.factor(as.character(fraud$fyear))
#fraud$period <- as.factor(fraud$period)
fraud$sich <- as.factor(fraud$sich)
fraud$gvkey <- as.character(fraud$gvkey)

fraud <- fraud[complete.cases(fraud),]

nonbenf <- fraud %>% select(-gvkey, -sich, -bf_1, -bf_2, -bf_3, -bf_agr)
benf <- fraud %>% select( -gvkey, -sich)

```


```{r}
# split the data into trainng (75%) and testing (25%)
set.seed(466581)
nonbenf_split <- initial_split(nonbenf, prop = 7/10, strata = misstate)
nonbenf_split

set.seed(466581)
benf_split <- initial_split(benf,prop = 3/4, strata = misstate)
benf_split

# extract training and testing sets
nonbenf_train <- training(nonbenf_split)
nonbenf_test <- testing(nonbenf_split)

benf_train <- training(benf_split)
benf_test <- testing(benf_split)

```


```{r}
# create validation set
nonbenf_cv <- vfold_cv(nonbenf_train, strata = misstate)

benf_cv<- vfold_cv(benf_train)
```


```{r}
logreg_recipe <- recipe(misstate ~ ., data = nonbenf_train) %>% 
  step_normalize(crt_ast, acc_pyb, ast,cmn_equ, cash, cogs, csho, crt_dbt, lt_db_is, lt_db, dpr_amrt,ibei, invt, ivao, st_inv, crt_liab, liab,
                 ni, ppe, pstk, re, receiv, sale) %>% 
  #step_rm(period, fyear) %>%
  step_impute_knn(all_predictors()) %>%
  step_downsample(misstate)


logreg_b_recipe <- recipe(misstate ~ ., data = benf_train) %>% 
  step_normalize(crt_ast, acc_pyb, ast,cmn_equ, cash, cogs, csho, crt_dbt, lt_db_is, lt_db, dpr_amrt,ibei, invt, ivao, st_inv, crt_liab, liab,
                ni, ppe, pstk, re, receiv, sale) %>% 
  #step_rm(period, fyear) %>%
  step_dummy(bf_1, bf_2, bf_3, bf_agr) %>%
  step_impute_knn(all_predictors()) %>%
  step_downsample(misstate)
```


```{r}
logreg_model <- logistic_reg(penalty = tune(), mixture = 0) %>% 
  set_engine("glmnet")


logreg_wf <- workflow() %>% 
  add_recipe(logreg_recipe) %>% 
  add_model(logreg_model)

logreg_b_wf <- workflow() %>% 
  add_recipe(logreg_b_recipe) %>% 
  add_model(logreg_model)


grid_ridge <- tibble(penalty = 10^(seq(from = -1, to = 4, length.out = 100)))

class_metrics <- metric_set(accuracy, sensitivity,
                            specificity, mcc, roc_auc, kap)

```


```{r}

ridge_tune <- logreg_wf %>% 
  tune_grid(resamples = nonbenf_cv, 
            grid = grid_ridge,
            metrics = class_metrics)



ridge_b_tune <- logreg_b_wf %>% 
  tune_grid(resamples = benf_cv, 
            grid = grid_ridge,
            metrics = class_metrics)

autoplot(ridge_tune)
autoplot(ridge_b_tune)
```


```{r}
ridge_1se_model <- select_by_one_std_err(ridge_tune, metric = "roc_auc", desc(penalty))
ridge_1se_model

ridge_1se_b_model <- select_by_one_std_err(ridge_b_tune, metric = "mcc", desc(penalty))
ridge_1se_b_model


ridge_b_metrics_sub <- ridge_b_tune %>% collect_metrics() %>% 
  pivot_wider(names_from = ".metric", 
              values_from = c("mean", "std_err")) %>% 
  filter(mean_mcc < 0.55) %>% 
  arrange(desc(mean_mcc))
ridge_b_metrics_sub

ridge_bf_selected <- ridge_b_metrics_sub %>% filter(.config == "Preprocessor1_Model037")



ridge_wf_tuned <- 
  logreg_wf %>% 
  finalize_workflow(ridge_1se_model)
ridge_wf_tuned


ridge_wf_b_tuned <- 
  logreg_b_wf %>% 
  finalize_workflow(ridge_bf_selected)
ridge_wf_b_tuned
```


```{r}
ridge_last_fit <- ridge_wf_tuned %>% 
  last_fit(nonbenf_split, metrics = class_metrics)

ridge_last_b_fit <- ridge_wf_b_tuned %>% 
  last_fit(benf_split, metrics = class_metrics)

ridge_test_metrics <- ridge_last_fit %>% collect_metrics()

ridge_test_b_metrics <- ridge_last_b_fit %>% collect_metrics()

ridge_test_pred <- ridge_last_fit %>% collect_predictions()

ridge_test_b_pred <- ridge_last_b_fit %>% collect_predictions()
  

nonbenf_pred <- nonbenf_test %>% mutate(ridge_nb_pred = ridge_test_pred$.pred_class)
benf_pred <- benf_test %>% mutate(ridge_b_pred = ridge_test_b_pred$.pred_class)

  
mcc_b_metric <- yardstick::mcc(benf_pred, truth = misstate, estimate = ridge_b_pred, event_level = "second")
mcc_nb_metric <- yardstick::mcc(nonbenf_pred, truth = misstate, estimate = ridge_nb_pred, event_level = "second")

mcc_b_metric$.estimate
mcc_nb_metric$.estimate


conf_mat(nonbenf_pred, truth = misstate, estimate = ridge_nb_pred)

conf_mat(benf_pred, truth = misstate, estimate = ridge_b_pred)

library(vip)

ridge_wf_tuned %>%
  fit(nonbenf_test) %>%
  pull_workflow_fit() %>%
  vi()  %>%
  mutate(
    Importance = abs(Importance),
    Variable = fct_reorder(Variable, Importance)
  ) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = NULL)


ridge_wf_b_tuned %>%
  fit(benf_test) %>%
  pull_workflow_fit() %>%
  vi() %>%
  mutate(
    Importance = abs(Importance),
    Variable = fct_reorder(Variable, Importance)
  ) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = NULL)

```

```{r}
library(yardstick)
```


